trigger:
  branches:
    include:
      - refs/tags/*
pr: none

resources:
  containers:
    - container: go-build-agent
      image: mclaren-cloudplatform-docker-dev-local.jfrog.io/golang:1.13
      endpoint: artifactory-cloud-mcp-docker
  repositories:
    - repository: common
      type: git
      name: ma.ci.common

variables:
  - group: condition-insight-dev

pool:
  name: 'ConditionInsight-Dev'

jobs:
  - job: build_and_publish
    container: go-build-agent
    displayName: Build
    steps:
      - template: build-templates/upload-to-artifactory.yml@common
        parameters:
          name: "{{.ApplicationName}}"
          type: "dev"
          packagingScript: "./build.sh"
